# Shared helpers for the Windows server scripts (dot-sourced by setup/start/autostart).
$ErrorActionPreference = "Stop"

$script:Root = Split-Path -Parent $PSScriptRoot
$script:EnvFile = Join-Path $script:Root ".env.production"
$script:CaddyFile = Join-Path $PSScriptRoot "Caddyfile"
$script:LogDir = Join-Path $PSScriptRoot "logs"

function Write-Step([string]$Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Ok([string]$Message) { Write-Host "    $Message" -ForegroundColor Green }
function Write-Warn([string]$Message) { Write-Host "    ! $Message" -ForegroundColor Yellow }

function Test-Admin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    return ([Security.Principal.WindowsPrincipal]$identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Reads KEY="value" lines into an ordered dictionary (comments and blanks are dropped).
function Read-EnvFile([string]$Path) {
    $values = [ordered]@{}
    if (-not (Test-Path $Path)) { return $values }
    foreach ($line in Get-Content -Path $Path -Encoding UTF8) {
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$') {
            $value = $Matches[2]
            if ($value.Length -ge 2 -and $value.StartsWith('"') -and $value.EndsWith('"')) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            $values[$Matches[1]] = $value
        }
    }
    return $values
}

function Write-EnvFile([string]$Path, $Values) {
    $lines = @("# Generated by deploy/setup.ps1 - safe to edit; re-run setup or restart the server to apply.")
    foreach ($key in $Values.Keys) { $lines += ('{0}="{1}"' -f $key, $Values[$key]) }
    [IO.File]::WriteAllLines($Path, $lines, (New-Object Text.UTF8Encoding($false)))
}

# Puts every value into the process environment so child processes (node, prisma) see it.
function Import-EnvFile([string]$Path) {
    $values = Read-EnvFile $Path
    foreach ($key in $values.Keys) { Set-Item -Path "Env:$key" -Value $values[$key] }
    return $values
}

function New-Secret([int]$Bytes = 32) {
    $buffer = New-Object byte[] $Bytes
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($buffer)
    $rng.Dispose()
    return [Convert]::ToBase64String($buffer).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

# The IPv4 address of the interface that carries the default route.
function Get-LocalIp {
    $route = Get-NetRoute -DestinationPrefix "0.0.0.0/0" -ErrorAction SilentlyContinue |
        Sort-Object { $_.RouteMetric + $_.InterfaceMetric } | Select-Object -First 1
    if ($route) {
        $address = Get-NetIPAddress -InterfaceIndex $route.InterfaceIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue |
            Where-Object { $_.IPAddress -notlike "169.254.*" } | Select-Object -First 1
        if ($address) { return $address.IPAddress }
    }
    $fallback = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } | Select-Object -First 1
    if ($fallback) { return $fallback.IPAddress }
    throw "Could not detect this computer's IP address. Pass it explicitly with -Ip."
}

# Best effort only - used to warn when the machine sits behind a router.
function Get-PublicIp {
    try { return (Invoke-RestMethod -Uri "https://api.ipify.org" -TimeoutSec 5).ToString().Trim() } catch { return $null }
}

function Find-Executable([string]$Name, [string[]]$ExtraPaths = @()) {
    $command = Get-Command $Name -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($command) { return $command.Source }
    foreach ($path in $ExtraPaths) { if ($path -and (Test-Path $path)) { return $path } }
    return $null
}

function Find-Caddy {
    return Find-Executable "caddy" @(
        (Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Links\caddy.exe"),
        (Join-Path $env:ProgramFiles "Caddy\caddy.exe"),
        "C:\caddy\caddy.exe"
    )
}

# Returns a description of whatever already listens on the port, or $null when it is free.
function Get-PortOwner([int]$Port) {
    $connection = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $connection) { return $null }
    $process = Get-Process -Id $connection.OwningProcess -ErrorAction SilentlyContinue
    if ($process) { return "$($process.ProcessName) (PID $($process.Id))" }
    return "PID $($connection.OwningProcess)"
}

# Caddy config: a real domain gets a trusted Let's Encrypt certificate automatically;
# a bare IP gets a certificate from Caddy's own CA (browsers show a warning for it).
function New-CaddyfileText([string]$Domain, [string]$Ip, [int]$AppPort) {
    $common = @"
	bind $Ip
	encode zstd gzip
	request_body {
		max_size 600MB
	}
	reverse_proxy 127.0.0.1:$AppPort
"@
    if ($Domain) {
        return @"
$Domain {
$common
	header {
		Strict-Transport-Security "max-age=31536000"
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
		-Server
	}
}
"@
    }
    return @"
{
	local_certs
	default_sni $Ip
}

https://$Ip {
	tls internal
$common
}
"@
}

# ---------------------------------------------------------------------------
# Background server state: start.ps1 (the supervisor) records what it runs here,
# so any terminal - even one opened much later - can find, inspect and stop it.
# ---------------------------------------------------------------------------
$script:StateFile = Join-Path $PSScriptRoot "state.json"
$script:StopFlag = Join-Path $PSScriptRoot "stop.flag"
$script:TaskName = "Lab3D Server"

function Get-ProcStart([int]$ProcessId) {
    try { return (Get-Process -Id $ProcessId -ErrorAction Stop).StartTime.ToUniversalTime().ToString("o") } catch { return $null }
}

# A PID alone can be reused by Windows; the start time makes the match exact.
function Test-ProcAlive($ProcessId, $StartedAt) {
    if (-not $ProcessId) { return $false }
    $actual = Get-ProcStart ([int]$ProcessId)
    if (-not $actual) { return $false }
    return (-not $StartedAt) -or ($actual -eq $StartedAt)
}

function Save-State($State) {
    [IO.File]::WriteAllText($script:StateFile, ($State | ConvertTo-Json -Depth 4), (New-Object Text.UTF8Encoding($false)))
}

function Read-State {
    if (-not (Test-Path $script:StateFile)) { return $null }
    try { return (Get-Content -Path $script:StateFile -Raw -Encoding UTF8 | ConvertFrom-Json) } catch { return $null }
}

# The state of the running server, or $null when it is not running.
function Get-ServerState {
    $state = Read-State
    if ($state -and (Test-ProcAlive $state.supervisorPid $state.supervisorStart)) { return $state }
    return $null
}

function ConvertTo-Utc($Value) {
    if ($Value -is [datetime]) { return $Value.ToUniversalTime() }
    return [DateTimeOffset]::Parse([string]$Value, [Globalization.CultureInfo]::InvariantCulture).UtcDateTime
}

# Starts a hidden process that belongs to nobody's console or job, so closing the
# terminal that launched it (or logging off the launching tool) does not kill it.
function Start-Detached([string]$CommandLine, [string]$WorkDir) {
    $startup = New-CimInstance -ClassName Win32_ProcessStartup -ClientOnly -Property @{ ShowWindow = [uint16]0 }
    $result = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{
        CommandLine = $CommandLine; CurrentDirectory = $WorkDir; ProcessStartupInformation = $startup
    }
    if ($result.ReturnValue -ne 0) { throw "Windows could not start the background process (code $($result.ReturnValue))." }
    return [int]$result.ProcessId
}

function Stop-ProcessTree($ProcessId) {
    if ($ProcessId) { & taskkill /PID $ProcessId /T /F 2>&1 | Out-Null }
}

# Stops the site: asks the supervisor to shut down cleanly, then forces it if it hangs.
function Stop-Server([int]$GraceSeconds = 15) {
    $state = Read-State
    if (-not $state) { return }

    if (Test-ProcAlive $state.supervisorPid $state.supervisorStart) {
        [IO.File]::WriteAllText($script:StopFlag, "stop")
        $deadline = (Get-Date).AddSeconds($GraceSeconds)
        while ((Get-Date) -lt $deadline -and (Test-ProcAlive $state.supervisorPid $state.supervisorStart)) { Start-Sleep -Milliseconds 300 }
        if (Test-ProcAlive $state.supervisorPid $state.supervisorStart) {
            # Stopping the task first keeps Task Scheduler from restarting it after the kill.
            Stop-ScheduledTask -TaskName $script:TaskName -ErrorAction SilentlyContinue
            Stop-ProcessTree $state.supervisorPid
        }
    }
    foreach ($child in @(@($state.nextPid, $state.nextStart), @($state.caddyPid, $state.caddyStart))) {
        if (Test-ProcAlive $child[0] $child[1]) { Stop-ProcessTree $child[0] }
    }
    Remove-Item $script:StopFlag, $script:StateFile -ErrorAction SilentlyContinue
}

function Get-AutostartTask { return Get-ScheduledTask -TaskName $script:TaskName -ErrorAction SilentlyContinue }

function Format-Size([double]$Bytes) {
    if ($Bytes -ge 1GB) { return ("{0:N1} ГБ" -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ("{0:N1} МБ" -f ($Bytes / 1MB)) }
    if ($Bytes -ge 1KB) { return ("{0:N0} КБ" -f ($Bytes / 1KB)) }
    return ("{0:N0} Б" -f $Bytes)
}

function Get-FolderSize([string]$Path) {
    if (-not (Test-Path $Path)) { return 0 }
    $sum = (Get-ChildItem -Path $Path -Recurse -File -Force -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    if ($sum) { return $sum }
    return 0
}
