# Общие хелперы для скриптов сервера (dot-source из setup/start/server/autostart).
# Основано на deploy/lib.ps1 New_Lab_3d - тот же проверенный паттерн, упрощено:
# нет своей сборки/Next.js/Prisma и нет собственного Caddy (используем общий у New_Lab_3d).
$ErrorActionPreference = "Stop"

try { [Console]::OutputEncoding = New-Object Text.UTF8Encoding($false) } catch { }
$env:GIT_TERMINAL_PROMPT = "0"
$env:GCM_INTERACTIVE = "never"

$script:Root = Split-Path -Parent $PSScriptRoot
$script:EnvFile = Join-Path $script:Root ".env"
$script:LogDir = Join-Path $PSScriptRoot "logs"

function Write-Step([string]$Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Ok([string]$Message) { Write-Host "    $Message" -ForegroundColor Green }
function Write-Warn([string]$Message) { Write-Host "    ! $Message" -ForegroundColor Yellow }

function Test-Admin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    return ([Security.Principal.WindowsPrincipal]$identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Reads KEY="value" lines into an ordered dictionary (comments and blanks are dropped).
function Read-EnvFile([string]$Path) {
    $values = [ordered]@{}
    if (-not (Test-Path $Path)) { return $values }
    foreach ($line in Get-Content -Path $Path -Encoding UTF8) {
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$') {
            $value = $Matches[2]
            if ($value.Length -ge 2 -and $value.StartsWith('"') -and $value.EndsWith('"')) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            $values[$Matches[1]] = $value
        }
    }
    return $values
}

function Write-EnvFile([string]$Path, $Values) {
    $lines = @("# Generated by deploy/setup.ps1 - safe to edit; re-run setup or restart the server to apply.")
    foreach ($key in $Values.Keys) { $lines += ('{0}="{1}"' -f $key, $Values[$key]) }
    [IO.File]::WriteAllLines($Path, $lines, (New-Object Text.UTF8Encoding($false)))
}

function Import-EnvFile([string]$Path) {
    $values = Read-EnvFile $Path
    foreach ($key in $values.Keys) { Set-Item -Path "Env:$key" -Value $values[$key] }
    return $values
}

function New-Secret([int]$Bytes = 32) {
    $buffer = New-Object byte[] $Bytes
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($buffer)
    $rng.Dispose()
    return [Convert]::ToBase64String($buffer).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Get-LocalIp {
    $route = Get-NetRoute -DestinationPrefix "0.0.0.0/0" -ErrorAction SilentlyContinue |
        Sort-Object { $_.RouteMetric + $_.InterfaceMetric } | Select-Object -First 1
    if ($route) {
        $address = Get-NetIPAddress -InterfaceIndex $route.InterfaceIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue |
            Where-Object { $_.IPAddress -notlike "169.254.*" } | Select-Object -First 1
        if ($address) { return $address.IPAddress }
    }
    $fallback = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } | Select-Object -First 1
    if ($fallback) { return $fallback.IPAddress }
    throw "Не удалось определить IP этого компьютера."
}

function Find-Executable([string]$Name, [string[]]$ExtraPaths = @()) {
    $command = Get-Command $Name -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($command) { return $command.Source }
    foreach ($path in $ExtraPaths) { if ($path -and (Test-Path $path)) { return $path } }
    return $null
}

function Find-Caddy {
    return Find-Executable "caddy" @(
        (Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Links\caddy.exe"),
        (Join-Path $env:ProgramFiles "Caddy\caddy.exe"),
        "C:\caddy\caddy.exe"
    )
}

function Get-PortOwner([int]$Port) {
    $connection = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $connection) { return $null }
    $process = Get-Process -Id $connection.OwningProcess -ErrorAction SilentlyContinue
    if ($process) { return "$($process.ProcessName) (PID $($process.Id))" }
    return "PID $($connection.OwningProcess)"
}

# lab не запускает свой Caddy - он использует уже работающий у New_Lab_3d (общий 80/443 на
# этом сервере). Свой site-блок кладём в его deploy/sites.d/, который тот сам импортирует
# (см. New_Lab_3d/deploy/lib.ps1, New-CaddyfileText) - на его стороне ничего больше не меняем.
function New-LabCaddySiteText([string]$Domain, [string]$Ip, [int]$AppPort) {
    return @"
$Domain {
	bind $Ip
	encode zstd gzip
	reverse_proxy 127.0.0.1:$AppPort
	header {
		Strict-Transport-Security "max-age=31536000"
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
		-Server
	}
}
"@
}

# ---------------------------------------------------------------------------
# Background server state: start.ps1 (the supervisor) records what it runs here.
# ---------------------------------------------------------------------------
$script:StateFile = Join-Path $PSScriptRoot "state.json"
$script:StopFlag = Join-Path $PSScriptRoot "stop.flag"
$script:TaskName = "Lab CRM Server"

function Get-ProcStart([int]$ProcessId) {
    try { return (Get-Process -Id $ProcessId -ErrorAction Stop).StartTime.ToUniversalTime().ToString("o") } catch { return $null }
}

function Test-ProcAlive($ProcessId, $StartedAt) {
    if (-not $ProcessId) { return $false }
    $actual = Get-ProcStart ([int]$ProcessId)
    if (-not $actual) { return $false }
    return (-not $StartedAt) -or ($actual -eq $StartedAt)
}

function Save-State($State) {
    [IO.File]::WriteAllText($script:StateFile, ($State | ConvertTo-Json -Depth 4), (New-Object Text.UTF8Encoding($false)))
}

function Read-State {
    if (-not (Test-Path $script:StateFile)) { return $null }
    try { return (Get-Content -Path $script:StateFile -Raw -Encoding UTF8 | ConvertFrom-Json) } catch { return $null }
}

function Get-ServerState {
    $state = Read-State
    if ($state -and (Test-ProcAlive $state.supervisorPid $state.supervisorStart)) { return $state }
    return $null
}

function ConvertTo-Utc($Value) {
    if ($Value -is [datetime]) { return $Value.ToUniversalTime() }
    return [DateTimeOffset]::Parse([string]$Value, [Globalization.CultureInfo]::InvariantCulture).UtcDateTime
}

function Start-Detached([string]$CommandLine, [string]$WorkDir) {
    $startup = New-CimInstance -ClassName Win32_ProcessStartup -ClientOnly -Property @{ ShowWindow = [uint16]0 }
    $result = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{
        CommandLine = $CommandLine; CurrentDirectory = $WorkDir; ProcessStartupInformation = $startup
    }
    if ($result.ReturnValue -ne 0) { throw "Windows не смог запустить фоновый процесс (код $($result.ReturnValue))." }
    return [int]$result.ProcessId
}

function Invoke-Native([scriptblock]$Command) {
    $previous = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $output = @(& $Command 2>&1 | ForEach-Object { "$_" })
        return [pscustomobject]@{ ExitCode = $LASTEXITCODE; Output = $output }
    }
    finally { $ErrorActionPreference = $previous }
}

function Stop-ProcessTree($ProcessId) {
    if ($ProcessId) { [void](Invoke-Native { & taskkill /PID $ProcessId /T /F }) }
}

function Stop-Server([int]$GraceSeconds = 15) {
    $state = Read-State
    if (-not $state) { return }

    if (Test-ProcAlive $state.supervisorPid $state.supervisorStart) {
        [IO.File]::WriteAllText($script:StopFlag, "stop")
        $deadline = (Get-Date).AddSeconds($GraceSeconds)
        while ((Get-Date) -lt $deadline -and (Test-ProcAlive $state.supervisorPid $state.supervisorStart)) { Start-Sleep -Milliseconds 300 }
        if (Test-ProcAlive $state.supervisorPid $state.supervisorStart) {
            Stop-ScheduledTask -TaskName $script:TaskName -ErrorAction SilentlyContinue
            Stop-ProcessTree $state.supervisorPid
        }
    }
    if (Test-ProcAlive $state.appPid $state.appStart) { Stop-ProcessTree $state.appPid }
    Remove-Item $script:StopFlag, $script:StateFile -ErrorAction SilentlyContinue
}

function Get-AutostartTask { return Get-ScheduledTask -TaskName $script:TaskName -ErrorAction SilentlyContinue }

function Format-Size([double]$Bytes) {
    if ($Bytes -ge 1GB) { return ("{0:N1} ГБ" -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ("{0:N1} МБ" -f ($Bytes / 1MB)) }
    if ($Bytes -ge 1KB) { return ("{0:N0} КБ" -f ($Bytes / 1KB)) }
    return ("{0:N0} Б" -f $Bytes)
}

function Get-FolderSize([string]$Path) {
    if (-not (Test-Path $Path)) { return 0 }
    $sum = (Get-ChildItem -Path $Path -Recurse -File -Force -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    if ($sum) { return $sum }
    return 0
}

# ---------------------------------------------------------------------------
# Git: обновление - git pull в своей папке (без сборки/миграций, их тут просто нет).
# ---------------------------------------------------------------------------
function Invoke-Git {
    $git = Find-Executable "git"
    if (-not $git) { throw "git не установлен (winget install Git.Git)." }
    $ErrorActionPreference = "Continue"
    $lines = & $git -c core.quotepath=off -c safe.directory=* -C $script:Root @args 2>&1 | ForEach-Object { "$_" }
    $script:GitExit = $LASTEXITCODE
    return @($lines)
}

function Get-GitInfo([switch]$NoFetch) {
    $info = [ordered]@{
        gitInstalled = [bool](Find-Executable "git"); isRepo = $false; hasCommits = $false; branch = ""; upstream = ""; remote = ""
        head = ""; headDate = ""; headMessage = ""; behind = 0; ahead = 0; dirty = 0; commits = @(); error = ""
    }
    if (-not $info.gitInstalled) { return $info }
    if (-not (Test-Path (Join-Path $script:Root ".git"))) { return $info }
    $info.isRepo = $true

    [void](Invoke-Git rev-parse --verify --quiet HEAD)
    $info.hasCommits = ($script:GitExit -eq 0)
    $remote = Invoke-Git remote get-url origin
    if ($script:GitExit -eq 0) { $info.remote = "$($remote | Select-Object -First 1)" }
    if (-not $info.hasCommits) { return $info }

    $branch = Invoke-Git rev-parse --abbrev-ref HEAD
    if ($script:GitExit -eq 0) { $info.branch = "$($branch | Select-Object -First 1)" }
    $log = @(Invoke-Git log -1 "--format=%h|%cd|%s" "--date=format:%d.%m.%Y %H:%M")
    if ($script:GitExit -eq 0 -and $log.Count -gt 0) {
        $parts = "$($log[0])".Split("|", 3)
        if ($parts.Count -eq 3) { $info.head = $parts[0]; $info.headDate = $parts[1]; $info.headMessage = $parts[2] }
    }
    $info.dirty = @(Invoke-Git status --porcelain -uno | Where-Object { $_ }).Count

    if (-not $NoFetch -and $info.remote) {
        $fetch = Invoke-Git fetch --quiet
        if ($script:GitExit -ne 0) { $info.error = ("$($fetch -join ' ')").Trim() }
    }
    $upstream = Invoke-Git rev-parse --abbrev-ref --symbolic-full-name "@{u}"
    if ($script:GitExit -eq 0) {
        $info.upstream = "$($upstream | Select-Object -First 1)"
        $behind = Invoke-Git rev-list --count "HEAD..@{u}"
        if ($script:GitExit -eq 0) { $info.behind = [int]"$($behind | Select-Object -First 1)" }
        $ahead = Invoke-Git rev-list --count "@{u}..HEAD"
        if ($script:GitExit -eq 0) { $info.ahead = [int]"$($ahead | Select-Object -First 1)" }
        $info.commits = @(Invoke-Git log "HEAD..@{u}" "--format=%h  %s" -n 30 | Where-Object { $_ })
    }
    return $info
}
